<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\pluginLib\pluginLib.csproj" />
    <ProjectReference Include="..\pluginAttribute\pluginAttribute.csproj" />
    <ProjectReference Include="..\plugin1\plugin1.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
