name: Build and Test

on:
  push:
    branches: ["main"] 
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x' 

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build solution
        run: dotnet build --configuration Release --no-restore 

      - name: Run tests
        run: dotnet test 
        